import type { DomainId } from "./types";

/**
 * «Заметка дня»: цитаты, законы, проверяемые факты и фольклор.
 * Правила (проверяет validate-content):
 *  - quote / law — обязательны автор и источник (работа, выступление, письмо, RFC; год);
 *  - fact — обязателен источник (стандарт, спецификация, документ);
 *  - folklore — безымянные шутки и пословицы, без выдуманной атрибуции;
 *  - attributed — приписываемая фраза без первоисточника: честно помечается.
 * Текст — на английском, смысловой перевод — в поле ru. Если у фразы есть тема, которая объясняет «почему так», она указана в topic.
 */
export type LoreKind = "quote" | "law" | "fact" | "folklore" | "attributed";

export interface Lore {
  id: string;
  kind: LoreKind;
  text: string;
  ru: string;
  author?: string;
  source?: string;
  domain: DomainId | "all";
  /** Полный id темы-объяснения, например "cs.complexity-big-o". */
  topic?: string;
}

export const LORE: Lore[] = [
  // ───────── CS и инженерия ─────────
  {
    id: "knuth-premature-optimization",
    kind: "quote",
    text: "We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil.",
    ru: "О мелкой эффективности стоит забыть примерно в 97 % случаев: преждевременная оптимизация — корень всех зол.",
    author: "Donald Knuth",
    source: "Structured Programming with go to Statements, Computing Surveys, 1974",
    domain: "cs",
    topic: "cs.complexity-big-o",
  },
  {
    id: "dijkstra-testing",
    kind: "quote",
    text: "Program testing can be used to show the presence of bugs, but never to show their absence!",
    ru: "Тестирование может показать присутствие ошибок, но никогда — их отсутствие.",
    author: "Edsger W. Dijkstra",
    source: "Notes on Structured Programming (EWD249), 1970",
    domain: "cs",
    topic: "cs.software-testing-design",
  },
  {
    id: "hoare-null",
    kind: "quote",
    text: "I call it my billion-dollar mistake. It was the invention of the null reference in 1965.",
    ru: "Я называю это своей ошибкой на миллиард долларов: изобретение нулевой ссылки в 1965 году.",
    author: "Tony Hoare",
    source: "Null References: The Billion Dollar Mistake, QCon London, 2009",
    domain: "cs",
    topic: "cs.types-memory-models",
  },
  {
    id: "hoare-two-ways",
    kind: "quote",
    text: "There are two ways of constructing a software design: one way is to make it so simple that there are obviously no deficiencies, and the other is to make it so complicated that there are no obvious deficiencies.",
    ru: "Есть два способа построить программную систему: сделать её настолько простой, что в ней очевидно нет изъянов, или настолько сложной, что изъяны не очевидны.",
    author: "C. A. R. Hoare",
    source: "The Emperor's Old Clothes, Turing Award Lecture, Communications of the ACM, 1981",
    domain: "all",
    topic: "cs.abstraction-modularity",
  },
  {
    id: "kernighan-debugging",
    kind: "quote",
    text: "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.",
    ru: "Отладка вдвое сложнее, чем написание кода. Поэтому, если вы пишете код настолько хитро, насколько можете, то по определению недостаточно умны, чтобы его отладить.",
    author: "Brian W. Kernighan",
    source: "The Elements of Programming Style, 1978",
    domain: "js",
    topic: "js.errors-debugging",
  },
  {
    id: "kernighan-print",
    kind: "quote",
    text: "The most effective debugging tool is still careful thought, coupled with judiciously placed print statements.",
    ru: "Самый эффективный инструмент отладки по-прежнему — внимательное размышление и аккуратно расставленные операторы вывода.",
    author: "Brian W. Kernighan",
    source: "Unix for Beginners, Bell Laboratories, 1979",
    domain: "js",
    topic: "js.errors-debugging",
  },
  {
    id: "sicp-people",
    kind: "quote",
    text: "Programs must be written for people to read, and only incidentally for machines to execute.",
    ru: "Программы нужно писать для чтения людьми и лишь между делом — для исполнения машинами.",
    author: "Harold Abelson and Gerald Jay Sussman",
    source: "Structure and Interpretation of Computer Programs, preface to the first edition, 1985",
    domain: "all",
    topic: "cs.abstraction-modularity",
  },
  {
    id: "fowler-humans",
    kind: "quote",
    text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    ru: "Любой дурак может написать код, понятный компьютеру. Хорошие программисты пишут код, понятный людям.",
    author: "Martin Fowler",
    source: "Refactoring: Improving the Design of Existing Code, 1999",
    domain: "all",
    topic: "js.testing-architecture",
  },
  {
    id: "torvalds-show-code",
    kind: "quote",
    text: "Talk is cheap. Show me the code.",
    ru: "Разговоры ничего не стоят. Покажите код.",
    author: "Linus Torvalds",
    source: "linux-kernel mailing list, 25 August 2000",
    domain: "git",
    topic: "git.commits-history",
  },
  {
    id: "torvalds-data-structures",
    kind: "quote",
    text: "Bad programmers worry about the code. Good programmers worry about data structures and their relationships.",
    ru: "Плохие программисты беспокоятся о коде. Хорошие — о структурах данных и связях между ними.",
    author: "Linus Torvalds",
    source: "git mailing list, 27 June 2006",
    domain: "cs",
    topic: "cs.arrays-linked-lists",
  },
  {
    id: "torvalds-git-name",
    kind: "quote",
    text: "I'm an egotistical bastard, and I name all my projects after myself. First Linux, now git.",
    ru: "Я эгоистичный тип и называю все проекты в свою честь. Сначала Linux, теперь git.",
    author: "Linus Torvalds",
    source: "Tech Talk: Linus Torvalds on git, Google, 2007",
    domain: "git",
    topic: "git.git-mental-model",
  },
  {
    id: "robertson-commit-often",
    kind: "quote",
    text: "Commit often, perfect later, publish once.",
    ru: "Коммитьте часто, доводите до совершенства потом, публикуйте один раз.",
    author: "Seth Robertson",
    source: "Git Best Practices (online guide)",
    domain: "git",
    topic: "git.interactive-rebase",
  },
  {
    id: "brooks-law",
    kind: "law",
    text: "Adding manpower to a late software project makes it later.",
    ru: "Добавление людей в отстающий программный проект замедляет его ещё сильнее.",
    author: "Fred Brooks",
    source: "The Mythical Man-Month, 1975 (Brooks's law)",
    domain: "git",
    topic: "git.remote-collaboration",
  },
  {
    id: "conway-law",
    kind: "law",
    text: "Any organization that designs a system will produce a design whose structure is a copy of the organization's communication structure.",
    ru: "Любая организация, проектирующая систему, создаёт проект, структура которого копирует структуру коммуникаций в этой организации.",
    author: "Melvin Conway",
    source: "How Do Committees Invent?, Datamation, April 1968 (Conway's law)",
    domain: "all",
    topic: "cs.abstraction-modularity",
  },
  {
    id: "goodhart-strathern",
    kind: "law",
    text: "When a measure becomes a target, it ceases to be a good measure.",
    ru: "Когда мера становится целью, она перестаёт быть хорошей мерой.",
    author: "Marilyn Strathern",
    source: "'Improving ratings': audit in the British University system, European Review, 1997 (Goodhart's law)",
    domain: "cs",
    topic: "cs.software-testing-design",
  },
  {
    id: "hofstadter-law",
    kind: "law",
    text: "It always takes longer than you expect, even when you take into account Hofstadter's Law.",
    ru: "Всё всегда занимает больше времени, чем вы ожидаете, даже если учесть закон Хофштадтера.",
    author: "Douglas Hofstadter",
    source: "Gödel, Escher, Bach: An Eternal Golden Braid, 1979",
    domain: "all",
    topic: "cs.recursion-dp",
  },
  {
    id: "postel-law",
    kind: "law",
    text: "Be conservative in what you do, be liberal in what you accept from others.",
    ru: "Будьте консервативны в том, что делаете, и либеральны в том, что принимаете от других.",
    author: "Jon Postel",
    source: "RFC 761, Transmission Control Protocol, 1980 (Postel's law)",
    domain: "html",
    topic: "html.parsing-dom",
  },
  {
    id: "hyrum-law",
    kind: "law",
    text: "With a sufficient number of users of an API, it does not matter what you promise in the contract: all observable behaviors of your system will be depended on by somebody.",
    ru: "Когда у API достаточно много пользователей, неважно, что обещано в контракте: от любого наблюдаемого поведения системы кто-нибудь станет зависеть.",
    author: "Hyrum Wright",
    source: "hyrumslaw.com (Hyrum's law)",
    domain: "all",
    topic: "cs.abstraction-modularity",
  },
  {
    id: "zawinski-law",
    kind: "law",
    text: "Every program attempts to expand until it can read mail. Those programs which cannot so expand are replaced by ones which can.",
    ru: "Каждая программа стремится расти, пока не научится читать почту. Те, что не могут, заменяются теми, что могут.",
    author: "Jamie Zawinski",
    source: "Zawinski's law of software envelopment",
    domain: "all",
  },
  {
    id: "lamport-distributed",
    kind: "quote",
    text: "A distributed system is one in which the failure of a computer you didn't even know existed can render your own computer unusable.",
    ru: "Распределённая система — это такая, в которой отказ компьютера, о существовании которого вы не знали, делает непригодным ваш собственный.",
    author: "Leslie Lamport",
    source: "email, 28 May 1987",
    domain: "cs",
    topic: "cs.transactions-consistency-theory",
  },
  {
    id: "karlton-two-hard",
    kind: "attributed",
    text: "There are only two hard things in Computer Science: cache invalidation and naming things.",
    ru: "В информатике есть только две сложные вещи: инвалидация кеша и выбор имён.",
    author: "attributed to Phil Karlton",
    domain: "cs",
    topic: "cs.tls-caching-cookies",
  },
  {
    id: "turing-short-distance",
    kind: "quote",
    text: "We can only see a short distance ahead, but we can see plenty there that needs to be done.",
    ru: "Мы видим лишь недалеко вперёд, но видим там немало того, что нужно сделать.",
    author: "Alan Turing",
    source: "Computing Machinery and Intelligence, Mind, 1950",
    domain: "all",
  },
  {
    id: "perlis-language",
    kind: "quote",
    text: "A language that doesn't affect the way you think about programming is not worth knowing.",
    ru: "Язык, который не меняет то, как вы думаете о программировании, не стоит изучать.",
    author: "Alan Perlis",
    source: "Epigrams on Programming, ACM SIGPLAN Notices, 1982",
    domain: "cs",
    topic: "cs.compilation-interpretation",
  },
  {
    id: "perlis-simplicity",
    kind: "quote",
    text: "Simplicity does not precede complexity, but follows it.",
    ru: "Простота не предшествует сложности, а следует за ней.",
    author: "Alan Perlis",
    source: "Epigrams on Programming, ACM SIGPLAN Notices, 1982",
    domain: "git",
    topic: "git.rebase",
  },
  {
    id: "pike-copying",
    kind: "quote",
    text: "A little copying is better than a little dependency.",
    ru: "Немного копирования лучше, чем немного зависимости.",
    author: "Rob Pike",
    source: "Go Proverbs, Gopherfest, 2015",
    domain: "js",
    topic: "js.modules-esm",
  },
  {
    id: "pike-fancy",
    kind: "quote",
    text: "Fancy algorithms are slow when n is small, and n is usually small.",
    ru: "Хитрые алгоритмы медленны, когда n мало, а n обычно мало.",
    author: "Rob Pike",
    source: "Notes on Programming in C, rule 3, 1989",
    domain: "cs",
    topic: "cs.complexity-big-o",
  },
  {
    id: "pike-data",
    kind: "quote",
    text: "Data dominates. If you've chosen the right data structures and organized things well, the algorithms will almost always be self-evident.",
    ru: "Главное — данные. Если выбраны верные структуры данных и всё хорошо организовано, алгоритмы почти всегда очевидны сами.",
    author: "Rob Pike",
    source: "Notes on Programming in C, rule 5, 1989",
    domain: "cs",
    topic: "cs.hash-tables",
  },
  {
    id: "kernighan-complexity",
    kind: "quote",
    text: "Controlling complexity is the essence of computer programming.",
    ru: "Управление сложностью — суть программирования.",
    author: "Brian W. Kernighan",
    source: "Software Tools, 1976",
    domain: "css",
    topic: "css.organizing-css",
  },
  {
    id: "knuth-proved-not-tried",
    kind: "quote",
    text: "Beware of bugs in the above code; I have only proved it correct, not tried it.",
    ru: "Остерегайтесь ошибок в этом коде: я лишь доказал его правильность, но не запускал.",
    author: "Donald Knuth",
    source: "memo to Peter van Emde Boas, 1977",
    domain: "js",
    topic: "js.testing-architecture",
  },
  {
    id: "knuth-art",
    kind: "quote",
    text: "Science is what we understand well enough to explain to a computer. Art is everything else we do.",
    ru: "Наука — это то, что мы понимаем достаточно хорошо, чтобы объяснить компьютеру. Искусство — всё остальное, что мы делаем.",
    author: "Donald Knuth",
    source: "Foreword to A=B, 1996",
    domain: "cs",
    topic: "cs.compilation-interpretation",
  },
  // ───────── HTML ─────────
  {
    id: "berners-lee-universality",
    kind: "quote",
    text: "The power of the Web is in its universality. Access by everyone regardless of disability is an essential aspect.",
    ru: "Сила Веба — в его универсальности. Доступ для всех независимо от особенностей здоровья — его существенное свойство.",
    author: "Tim Berners-Lee",
    source: "W3C, launch of the Web Accessibility Initiative, 1997",
    domain: "html",
    topic: "html.a11y-fundamentals",
  },
  {
    id: "html-never-fails",
    kind: "fact",
    text: "HTML has no syntax errors. The parsing algorithm defines exactly what to do with every possible input, however broken.",
    ru: "В HTML нет синтаксических ошибок: алгоритм разбора точно определяет, что делать с любым входом, каким бы испорченным он ни был.",
    source: "WHATWG HTML Standard, section Parsing HTML documents",
    domain: "html",
    topic: "html.parsing-dom",
  },
  {
    id: "html-teapot",
    kind: "fact",
    text: "HTTP status 418 \"I'm a teapot\" comes from an April Fools' RFC about a coffee-pot control protocol.",
    ru: "Статус HTTP 418 «Я — чайник» происходит из первоапрельского RFC о протоколе управления кофейником.",
    source: "RFC 2324, Hyper Text Coffee Pot Control Protocol, 1 April 1998",
    domain: "html",
    topic: "cs.dns-http",
  },
  // ───────── CSS ─────────
  {
    id: "css1",
    kind: "fact",
    text: "CSS level 1 became a W3C Recommendation in December 1996 — a year after JavaScript's first release.",
    ru: "CSS первого уровня стал рекомендацией W3C в декабре 1996 года — спустя год после первого выпуска JavaScript.",
    source: "W3C, Cascading Style Sheets, level 1, Recommendation, 17 December 1996",
    domain: "css",
    topic: "css.how-css-works",
  },
  {
    id: "css-id-beats-classes",
    kind: "fact",
    text: "In CSS an ID selector beats any number of class selectors: specificity is compared as a tuple, not added up.",
    ru: "В CSS селектор по идентификатору побеждает любое число селекторов по классу: специфичность сравнивается как кортеж, а не суммируется.",
    source: "CSS Selectors Level 4, section Calculating a selector's specificity",
    domain: "css",
    topic: "css.specificity",
  },
  {
    id: "css-auto-margins",
    kind: "fact",
    text: "In normal block flow, auto margins center a box horizontally but never vertically. Flexbox and Grid ended that.",
    ru: "В обычном блочном потоке автоматические поля центрируют блок по горизонтали, но не по вертикали. Flexbox и Grid положили этому конец.",
    source: "CSS 2.1, section 10.6.3 (block-level, non-replaced elements in normal flow)",
    domain: "css",
    topic: "css.margin-collapsing",
  },
  // ───────── JavaScript ─────────
  {
    id: "crockford-misunderstood",
    kind: "quote",
    text: "JavaScript: The World's Most Misunderstood Programming Language.",
    ru: "JavaScript — самый непонятый в мире язык программирования.",
    author: "Douglas Crockford",
    source: "essay, 2001",
    domain: "js",
    topic: "js.what-is-js",
  },
  {
    id: "js-ten-days",
    kind: "fact",
    text: "The first JavaScript prototype was written in ten days in May 1995 — and its quirks have been backward-compatible ever since.",
    ru: "Первый прототип JavaScript был написан за десять дней в мае 1995 года, и его странности с тех пор сохраняются ради обратной совместимости.",
    source: "Brendan Eich, JavaScript at Ten Years, ICFP, 2005",
    domain: "js",
    topic: "js.what-is-js",
  },
  {
    id: "js-nan",
    kind: "fact",
    text: "typeof NaN is \"number\", and NaN is the only value not equal to itself.",
    ru: "typeof NaN равно «number», а NaN — единственное значение, не равное самому себе.",
    source: "ECMAScript Language Specification, typeof operator and IsStrictlyEqual",
    domain: "js",
    topic: "js.operators-coercion",
  },
  {
    id: "js-array-plus-object",
    kind: "fact",
    text: "In JavaScript, [] + {} is the string \"[object Object]\": both operands become strings first, then concatenate.",
    ru: "В JavaScript [] + {} — это строка «[object Object]»: оба операнда сначала приводятся к строкам, затем склеиваются.",
    source: "ECMAScript Language Specification, the addition operator and ToPrimitive",
    domain: "js",
    topic: "js.operators-coercion",
  },
  {
    id: "js-sort",
    kind: "fact",
    text: "[10, 9, 1].sort() returns [1, 10, 9]: without a comparator, elements are sorted as strings.",
    ru: "[10, 9, 1].sort() возвращает [1, 10, 9]: без функции сравнения элементы сортируются как строки.",
    source: "ECMAScript Language Specification, Array.prototype.sort",
    domain: "js",
    topic: "js.arrays",
  },
  // ───────── SQL ─────────
  {
    id: "codd-relational",
    kind: "quote",
    text: "Future users of large data banks must be protected from having to know how the data is organized in the machine.",
    ru: "Будущих пользователей больших банков данных нужно избавить от необходимости знать, как данные организованы внутри машины.",
    author: "E. F. Codd",
    source: "A Relational Model of Data for Large Shared Data Banks, Communications of the ACM, 1970",
    domain: "sql",
    topic: "sql.relational-model",
  },
  {
    id: "sql-null-equals-null",
    kind: "fact",
    text: "In SQL, NULL = NULL is not true. It is unknown — and WHERE keeps only rows where the condition is true.",
    ru: "В SQL выражение NULL = NULL — не истина, а «неизвестно», а WHERE оставляет только строки, где условие истинно.",
    source: "ISO/IEC 9075 (SQL), three-valued logic",
    domain: "sql",
    topic: "sql.data-types-null",
  },
  {
    id: "sql-not-in-null",
    kind: "fact",
    text: "x NOT IN (subquery) returns no rows at all if the subquery returns even one NULL.",
    ru: "x NOT IN (подзапрос) не вернёт ни одной строки, если подзапрос вернул хотя бы один NULL.",
    source: "ISO/IEC 9075 (SQL), three-valued logic",
    domain: "sql",
    topic: "sql.subqueries",
  },
  {
    id: "sql-bar-joke",
    kind: "folklore",
    text: "A SQL query walks into a bar, walks up to two tables and asks: \"Can I join you?\"",
    ru: "SQL-запрос заходит в бар, подходит к двум столикам и спрашивает: «Можно к вам присоединиться (JOIN)?»",
    domain: "sql",
    topic: "sql.inner-left-joins",
  },
  {
    id: "sql-clue",
    kind: "folklore",
    text: "SELECT * FROM users WHERE clue > 0;  — 0 rows returned.",
    ru: "SELECT * FROM users WHERE clue > 0;  — возвращено 0 строк.",
    domain: "sql",
    topic: "sql.select-where",
  },
  // ───────── Git ─────────
  {
    id: "git-content-addressing",
    kind: "fact",
    text: "A Git commit is named by the hash of its content. Change anything — message, author, parent — and you get a different commit.",
    ru: "Коммит в Git называется хешем своего содержимого. Измените что угодно — сообщение, автора, родителя — и получится другой коммит.",
    source: "Pro Git, chapter 10, Git Internals — Git Objects",
    domain: "git",
    topic: "git.objects-content-addressing",
  },
  // ───────── CS ─────────
  {
    id: "binary-search-bug",
    kind: "fact",
    text: "Binary search was published in 1946, but the first published version without bugs appeared only in 1962.",
    ru: "Бинарный поиск был описан в 1946 году, но первая опубликованная версия без ошибок появилась только в 1962-м.",
    source: "Donald Knuth, The Art of Computer Programming, vol. 3, section 6.2.1",
    domain: "cs",
    topic: "cs.searching-sorting",
  },
  {
    id: "ieee754-point-three",
    kind: "fact",
    text: "In IEEE 754 binary64, 0.1 + 0.2 is 0.30000000000000004. That is not a bug: 0.1 has no exact binary representation.",
    ru: "В IEEE 754 binary64 сумма 0.1 + 0.2 равна 0.30000000000000004. Это не ошибка: у 0.1 нет точного двоичного представления.",
    source: "IEEE 754-2019, binary64 format",
    domain: "cs",
    topic: "cs.number-systems-encoding",
  },
  {
    id: "unix-2038",
    kind: "fact",
    text: "A signed 32-bit Unix time counter overflows on 19 January 2038, at 03:14:07 UTC.",
    ru: "Знаковый 32-битный счётчик времени Unix переполняется 19 января 2038 года в 03:14:07 UTC.",
    source: "POSIX.1-2017, Seconds Since the Epoch",
    domain: "cs",
    topic: "cs.number-systems-encoding",
  },
  {
    id: "binary-joke",
    kind: "folklore",
    text: "There are 10 types of people in the world: those who understand binary and those who don't.",
    ru: "В мире существует 10 типов людей: те, кто понимает двоичную систему, и те, кто нет.",
    domain: "cs",
    topic: "cs.number-systems-encoding",
  },
  {
    id: "recursion-joke",
    kind: "folklore",
    text: "To understand recursion, you must first understand recursion.",
    ru: "Чтобы понять рекурсию, нужно сначала понять рекурсию.",
    domain: "cs",
    topic: "cs.recursion-dp",
  },
  {
    id: "qa-bar-joke",
    kind: "folklore",
    text: "A QA engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 99999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.",
    ru: "Тестировщик заходит в бар. Заказывает пиво. Заказывает 0 пив. Заказывает 99999999999 пив. Заказывает ящерицу. Заказывает −1 пиво. Заказывает «ывфдщлкнгшвц».",
    domain: "cs",
    topic: "cs.software-testing-design",
  },
  {
    id: "arpanet-lo",
    kind: "fact",
    text: "The first message ever sent over ARPANET, on 29 October 1969, was \"LO\": the system crashed before \"LOGIN\" was complete.",
    ru: "Первым сообщением в ARPANET 29 октября 1969 года было «LO»: система упала раньше, чем набралось «LOGIN».",
    source: "Leonard Kleinrock, UCLA, account of the first ARPANET transmission",
    domain: "cs",
    topic: "cs.network-model-ip-tcp",
  },
  {
    id: "dns-root",
    kind: "fact",
    text: "The DNS root is served under thirteen names, a.root-servers.net to m.root-servers.net — each backed by many machines worldwide via anycast.",
    ru: "Корень DNS обслуживается под тринадцатью именами, от a.root-servers.net до m.root-servers.net, и за каждым стоит множество машин по всему миру (anycast).",
    source: "IANA, Root Servers; RFC 4786, Operation of Anycast Services",
    domain: "cs",
    topic: "cs.dns-http",
  },
  {
    id: "byte-stretch",
    kind: "fact",
    text: "The word \"byte\" was coined in 1956 for IBM's Stretch computer; the eight-bit byte became the norm with IBM System/360.",
    ru: "Слово «байт» придумали в 1956 году для компьютера IBM Stretch; восьмибитный байт стал нормой с IBM System/360.",
    source: "Werner Buchholz, Planning a Computer System, 1962",
    domain: "cs",
    topic: "cs.number-systems-encoding",
  },
];

/** Номер дня от начала эпохи в местной дате — выбирает «заметку дня». */
export function dayNumber(date: Date): number {
  return Math.floor(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86_400_000);
}

/** Заметка дня: одна и та же в течение суток; для домена — из его пула и общих. */
export function loreOfDay(date: Date, domain?: DomainId): Lore {
  const pool = domain ? LORE.filter((l) => l.domain === domain || l.domain === "all") : LORE;
  return pool[dayNumber(date) % pool.length]!;
}
