import type { Topic } from "../../types";
import { howCssWorks } from "./how-css-works";
import { selectors } from "./selectors";
import { pseudoClassesElements } from "./pseudo-classes-elements";
import { cascade } from "./cascade";
import { specificity } from "./specificity";
import { inheritanceValues } from "./inheritance-values";
import { unitsMath } from "./units-math";
import { colors } from "./colors";
import { boxModel } from "./box-model";
import { displayFlow } from "./display-flow";
import { marginCollapsing } from "./margin-collapsing";
import { overflowSizing } from "./overflow-sizing";
import { typography } from "./typography";
import { positioning } from "./positioning";
import { containingBlock } from "./containing-block";
import { stackingContexts } from "./stacking-contexts";
import { flexboxBasics } from "./flexbox-basics";
import { flexSizing } from "./flex-sizing";
import { flexboxPatterns } from "./flexbox-patterns";
import { gridBasics } from "./grid-basics";
import { gridAreasPlacement } from "./grid-areas-placement";
import { gridResponsive } from "./grid-responsive";
import { subgridAlignment } from "./subgrid-alignment";
import { mediaQueries } from "./media-queries";
import { fluidTypographySpacing } from "./fluid-typography-spacing";
import { containerQueries } from "./container-queries";
import { responsiveMedia } from "./responsive-media";
import { customProperties } from "./custom-properties";
import { isWhereHas } from "./is-where-has";
import { logicalProperties } from "./logical-properties";
import { cascadeLayers } from "./cascade-layers";
import { nestingModern } from "./nesting-modern";
import { transitions } from "./transitions";
import { keyframes } from "./keyframes";
import { transforms } from "./transforms";
import { animationPerformanceMotion } from "./animation-performance-motion";
import { organizingCss } from "./organizing-css";
import { methodologies } from "./methodologies";
import { designTokens } from "./design-tokens";
import { specificityManagement } from "./specificity-management";
import { renderingPipeline } from "./rendering-pipeline";

/** Темы домена в порядке изучения. Порядок определяет состав модулей. */
export const cssTopics: Topic[] = [howCssWorks, selectors, pseudoClassesElements, cascade, specificity, inheritanceValues, unitsMath, colors, boxModel, displayFlow, marginCollapsing, overflowSizing, typography, positioning, containingBlock, stackingContexts, flexboxBasics, flexSizing, flexboxPatterns, gridBasics, gridAreasPlacement, gridResponsive, subgridAlignment, mediaQueries, fluidTypographySpacing, containerQueries, responsiveMedia, customProperties, isWhereHas, logicalProperties, cascadeLayers, nestingModern, transitions, keyframes, transforms, animationPerformanceMotion, organizingCss, methodologies, designTokens, specificityManagement, renderingPipeline];
